server:
  port: 5555
spring:
  application:
    name: market-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8090
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8091
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8092
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
            - JwtAuthFilter

jwt:
  secret: 5agwerDFHgp0weg703utjSFJDshbsHHio3njc234rypnc998t7bhn36AZBNGUK34056jvg0359DBGNJDTN4vnt035tn938457v