server:
  port: 8092
  servlet:
    context-path: /market-carts

integrations:
  product-service:
    url: http://localhost:8090/market-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
