server:
  port: 8090
  servlet:
    context-path: /market-core

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/GMarket
    username: postgres
    password: qqq
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  main:
    allow-circular-references: true

integrations:
  product-service:
    url: http://localhost:8092/market-carts/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000